/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectopoo;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author IanDa
 */
public class Pantalla7 extends javax.swing.JFrame {
     DefaultTableModel Ta = new DefaultTableModel();
     

    /**
     * Creates new form Pantalla7
     */
    public Pantalla7() {
        initComponents();
        TablaCorte.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {},
        new String [] {
        "cliente", "articulos", "costo", "piezas", "total"
    }
));

        
    }
private void cargarDatosCorte() {
    DefaultTableModel modelo = (DefaultTableModel) TablaCorte.getModel();
    modelo.setRowCount(0); // Limpiar la tabla antes de cargar datos

    File folder = new File("src/textos/");
    File[] listOfFiles = folder.listFiles((dir, name) -> name.endsWith("Corte.txt"));

    if (listOfFiles != null) {
        for (File file : listOfFiles) {
            System.out.println("Cargando datos del archivo: " + file.getName());
            try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
                String line;
                // Leer y descartar la primera línea de encabezado
                line = reader.readLine();
                while ((line = reader.readLine()) != null) {
                    String[] datos = line.split(" ");
                    if (datos.length == 5) {
                        modelo.addRow(datos);
                        System.out.println("Datos agregados: " + String.join(", ", datos));
                    } else {
                        System.out.println("Línea inválida: " + line);
                    }
                }
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    } else {
        System.out.println("No se encontraron archivos de corte.");
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaCorte = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnCargarCorte = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        btnTotal1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        TablaCorte.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        TablaCorte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "cliente", "articulos", "costo", "piezas", "total"
            }
        ));
        jScrollPane1.setViewportView(TablaCorte);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 3, 36)); // NOI18N
        jLabel1.setText("CORTE");

        btnCargarCorte.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        btnCargarCorte.setText("Cargar Corte");
        btnCargarCorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarCorteActionPerformed(evt);
            }
        });

        btnInicio.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        btnInicio.setText("Inicio");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        btnTotal1.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        btnTotal1.setText("Total");
        btnTotal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotal1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(377, 377, 377))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(btnTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(btnCargarCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCargarCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
        Pantalla1 datos = new Pantalla1();
        datos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnCargarCorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarCorteActionPerformed
       cargarDatosCorte();
        
    }//GEN-LAST:event_btnCargarCorteActionPerformed

    private void btnTotal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotal1ActionPerformed
        Pantalla8 p8 = new Pantalla8();
        p8.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTotal1ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void cargarDatos() {
    String archivo = "C:\\Users\\301-PC2\\Desktop\\alumnos.txt";
    File file = new File(archivo);
    try {
        BufferedReader lector = new BufferedReader(new FileReader(file));
        Object[] linea = lector.lines().toArray();
        DefaultTableModel modelo = (DefaultTableModel) TablaCorte.getModel();
        modelo.setRowCount(0); // Limpiar tabla antes de cargar datos
        for (int i = 0; i < linea.length; i++) {
            String dato = linea[i].toString();
            String texto[] = dato.split(" ");
            modelo.addRow(texto);
        }
    } catch (IOException e) {
        
    }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaCorte;
    private javax.swing.JButton btnCargarCorte;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnTotal1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
